### ISSUE TITLE
Relationship arrows not displaying in IE11

### ISSUE THREAD

**Issue by StephenThomson** [oasis-open/cti-stix-visualization#27] opened 2018-01-09 16:12 UTC
In IE11 the link arrows between nodes do not display correctly. If you update the stylesheet in developer tools they appear but remain in place if you move a node.

Also it is possible to drag nodes out of the canvas onto any section of the page.

**Comment by gtback** [comment] 2018-01-10 22:19
Thanks, @StephenThomson. I'll have to dig up a Windows box to test this, but it's definitely something we should fix 😁

**Comment by StephenThomson** [comment] 2018-01-11 09:58
Thanks Greg! Sorry to cause you to have do that. I wish I didn't have to support IE too :)

**Comment by StephenThomson** [comment] 2018-05-23 10:00
Hi Greg,

Just wondering if there's any progress/plans on this issue?

If the answer is "go fix it yourself" I would completely understand! haha

Steve

**Comment by gtback** [comment] 2018-05-24 16:19
Hi, @StephenThomson . No updates, sorry. If you have time and are able to fix this, it would be much appreciated! I'm not sure when we'll be able to do it ourselves.

**Comment by gleithall** [comment] 2018-07-24 11:57
The lack of lines connecting the nodes is caused by a known issue for IE 10 and 11 relating to SVG paths not rendering when they have markers.

We have a fork of the code in which both the arrow heads and shafts are drawn using SVG paths, rather than using marker definitions. The only difference is that the whole arrows are the same colour, rather than the arrow heads being black and the arrow shafts being grey.

I can look to create a branch of the current codebase and submit a PR if this fix would be useful.

**Comment by gtback** [comment] 2018-07-24 13:43
Hi @gleithall . We would welcome a PR! You'll need to sign the [OASIS TC Open Repository Individual CLA](https://www.oasis-open.org/resources/open-repositories/cla/individual-cla) before we can merge anything. Let us know if you have any concerns.

I'm not particularly worries about the different colors, but I'm not a UI expert :-)

**Comment by StephenThomson** [comment] 2018-07-24 14:33
@gtback I believe we signed one as an organisation for a previous contribution.
@gleithall I think you can fork into the CACI org, make your changes there then do a PR on behalf of CACI.

**Comment by gtback** [comment] 2018-07-24 14:45
@StephenThomson you have a signed CLA on [this page](https://www.oasis-open.org/resources/open-repositories/cla/view-individual), but we need one from each person who is making commits that go into the repo. Thanks!

**Comment by gleithall** [comment] 2018-07-24 16:31
@gtback I have created PR #31 for this issue. I have also signed the CLA.

**Comment by gtback** [comment] 2018-07-24 16:43
Thanks, @gleithall. I think there's some background work at OASIS to confirm the CLA, but after that your PR should be good to merge!

**Comment by gleithall** [comment] 2018-07-25 08:43
@gtback My CLA has now been processed, and appears on the page you referenced earlier.

**Comment by gtback** [comment] 2018-07-25 15:16
Fixed by #31

**Closed as completed by gtback** 2018-07-25 15:16 UTC
Labels: bug
